services:
  - type: web
    name: apo-orchestrator-1
    env: python
    plan: starter
    autoDeploy: true

    buildCommand: pip install -r requirements.txt

    # Auto-init plików na dysku + start serwera
    startCommand: >
      bash -lc '
      mkdir -p /var/apo;
      [ -f "/var/apo/bulletin.json" ] || printf "{\n  \"items\": [],\n  \"updated_at\": null\n}\n" > /var/apo/bulletin.json;
      [ -f "/var/apo/denylist.json" ] || printf "{\n  \"patterns\": []\n}\n" > /var/apo/denylist.json;
      uvicorn main:app --host 0.0.0.0 --port $PORT
      '

    # MOUNT: /var/apo (zamiast /data)
    disk:
      name: apo-data
      mountPath: /var/apo
      sizeGB: 1

    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: APO_ADMIN_KEY
        sync: false
      - key: BULLETIN_PATH
        value: /var/apo/bulletin.json
      - key: APO_KB_DENYLIST_PATH
        value: /var/apo/denylist.json
      - key: KNOWLEDGE_INDEX_PATH
        value: index.json
      - key: LLM_DEFAULT_MODEL
        value: openai/gpt-4o
      - key: LLM_PLANNER_MODEL
        value: mistralai/mistral-7b-instruct:free
      - key: RATE_LIMIT_ENABLED
        value: "true"
      - key: RATE_LIMIT_RPM
        value: "120"
      - key: LEGAL_STATUS_DEFAULT_DATE
        value: "1 września 2025 r."
      - key: PUBLIC_BASE_URL
        value: https://apo-orchestrator-1.onrender.com

schedules:
  # CRON 2×/dobę: 06:00 i 18:00 UTC
  - name: refresh-public-sources-morning
    type: cron
    schedule: "0 6 * * *"
    env: python
    plan: starter
    command: >
      bash -lc
      "curl -fsS -X POST -H \"X-APO-Key: $APO_ADMIN_KEY\"
      \"$PUBLIC_BASE_URL/admin/refresh-public-sources\" || true"

  - name: refresh-public-sources-evening
    type: cron
    schedule: "0 18 * * *"
    env: python
    plan: starter
    command: >
      bash -lc
      "curl -fsS -X POST -H \"X-APO-Key: $APO_ADMIN_KEY\"
      \"$PUBLIC_BASE_URL/admin/refresh-public-sources\" || true"

  # CRON raz w tygodniu: niedziela 21:30 UTC
  - name: refresh-public-sources-weekly
    type: cron
    schedule: "30 21 * * 0"
    env: python
    plan: starter
    command: >
      bash -lc
      "curl -fsS -X POST -H \"X-APO-Key: $APO_ADMIN_KEY\"
      \"$PUBLIC_BASE_URL/admin/refresh-public-sources\" || true"